version: '3.8'

services:
  db:
    image: postgres:14-bullseye
    restart: on-failure
    environment:
      POSTGRES_DB: antipoaching
      POSTGRES_USER_FILE: /run/secrets/pg_user
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - pg_password
      - pg_user

  analytics:
    image: pig208/anti-poaching-analytics-dev:${REVISION:-latest}
    build:
      context: analytics
      target: development
      args:
        REQUIREMENTS_TXT: requirements/dev.txt

  api:
    image: pig208/anti-poaching-api-dev:${REVISION:-latest}
    build:
      context: api
      args:
        REQUIREMENTS_TXT: requirements/dev.txt
    ports:
      - 8000:8000
    restart: on-failure
    depends_on: 
      - db
    environment:
      PG_HOST: db
      PG_DBNAME: antipoaching
      PG_TESTDBNAME: pytest
    secrets:
      - pg_password
      - pg_user

volumes:
    pgdata:

secrets:
    pg_password:
      file: secrets/dev/pg_password
    pg_user:
      file: secrets/dev/pg_user
