version: '3.8'

services:
  analytics:
    image: pig208/anti-poaching-analytics-prod:latest
    build:
      context: analytics
      target: production-base
      dockerfile: ../shared/poetry.Dockerfile
    command: ["echo", "running"]

volumes:
    data:
