version: '3.8'

services:
  analytics-lint:
    build:
      context: .
      dockerfile: shared/lint.Dockerfile
      args:
        SOURCE_DIR: analytics
        REQUIREMENTS_TXT: analytics/requirements/dev.txt
    environment:
      TARGET_DIR: /opt/app/analytics
    volumes:
      - ./analytics/analytics:/opt/app/analytics

  api-lint:
    build:
      context: .
      dockerfile: shared/lint.Dockerfile
      args:
        SOURCE_DIR: api
        REQUIREMENTS_TXT: api/requirements/dev.txt
    environment:
      TARGET_DIR: /opt/app
    volumes:
      - ./api:/opt/app
