version: '3.8'

services:
  db:
    image: postgres:14-bullseye
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      POSTGRES_DB: antipoaching
      POSTGRES_USER: passerine
      POSTGRES_PASSWORD: development_password

  analytics:
    image: pig208/anti-poaching-analytics-dev:latest
    build:
      context: analytics
      target: development-base
      dockerfile: ../shared/poetry.Dockerfile

volumes:
    data:
