version: '3.1'

services:
  db:
    image: postgres:14-bullseye
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      POSTGRES_DB: antipoaching
      POSTGRES_USER: passerine
      POSTGRES_PASSWORD: development_password

volumes:
    data:
