version: '3.8'

services:
  analytics:
    volumes:
      - ./analytics/analytics:/opt/app/analytics

  api:
    volumes:
      - ./api/api:/opt/app/api
      - ./api/alembic:/opt/app/alembic
      - ./api/alembic.ini:/opt/app/alembic.ini
