version: '3.8'

services:
  analytics:
    image: pig208/anti-poaching-analytics-prod:${REVISION:-latest}
    build:
      context: .
      dockerfile: analytics/Dockerfile
      target: production
    secrets:
      - pg_user
      - pg_password

  api:
    image: pig208/anti-poaching-api-dev:${REVISION:-latest}
    build:
      context: .
      dockerfile: api/Dockerfile
      target: production
    secrets:
      - pg_user
      - pg_password

secrets:
    pg_password:
      file: secrets/prod/pg_password
    pg_user:
      file: secrets/prod/pg_user
