version: '3.8'

services:
  analytics:
    image: pig208/anti-poaching-analytics-prod:${REVISION:-latest}
    build:
      context: .
      dockerfile: analytics/Dockerfile
      target: production
      args: 
        SERVICE_ROOT: analytics

volumes:
    data:
