version: '3.8'

services:
  analytics:
    image: pig208/anti-poaching-analytics-prod:${REVISION:-latest}
    build:
      context: .
      dockerfile: analytics/Dockerfile
      target: production
      args: 
        SERVICE_ROOT: analytics
    secrets:
      - pg_password

secrets:
    pg_password:
      file: secrets/prod/pg_password
    pg_user:
      file: secrets/prod/pg_user