version: '3.8'

services:
  lint-analytics:
    build:
      context: .
      dockerfile: shared/lint.Dockerfile
      args:
        SOURCE_DIR: analytics
        REQUIREMENTS_TXT: analytics/requirements/dev.txt
    environment:
      TARGET_DIR: /opt/app/analytics
    volumes:
      - ./analytics/analytics:/opt/app/analytics

  lint-api:
    build:
      context: .
      dockerfile: shared/lint.Dockerfile
      args:
        SOURCE_DIR: api
        REQUIREMENTS_TXT: api/requirements/dev.txt
    environment:
      TARGET_DIR: /opt/app/api
    volumes:
      - ./api/api:/opt/app/api
      - ./api/alembic:/opt/app/api/alembic
