version: '3.8'

services:
  api:
    depends_on:
      - db-test
    volumes:
      - ./api:/opt/app

  client:
    build:
      context: .
      dockerfile: shared/client.Dockerfile
    volumes:
      - ./client:/client/home
    depends_on:
      - api
