version: '3.8'

services:
  db:
    image: postgres:14-bullseye
    restart: always
    environment:
      POSTGRES_DB: antipoaching
      POSTGRES_USER_FILE: /run/secrets/pg_user
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - pg_password
      - pg_user

  analytics:
    image: pig208/anti-poaching-analytics-dev:${REVISION:-latest}
    build:
      context: .
      dockerfile: analytics/Dockerfile
      target: development
      args:
        SERVICE_ROOT: analytics
        SOURCE_DIRNAME: analytics

  api:
    image: pig208/anti-poaching-api-dev:${REVISION:-latest}
    build:
      context: .
      dockerfile: api/Dockerfile
      target: development
      args:
        SERVICE_ROOT: api
        SOURCE_DIRNAME: api

volumes:
    pgdata:

secrets:
    pg_password:
      file: secrets/dev/pg_password
    pg_user:
      file: secrets/dev/pg_user
