version: '3.8'

services:
  analytics-lint:
    build:
      context: .
      dockerfile: shared/lint.Dockerfile
      args:
        SOURCE_DIR: analytics-cli
        REQUIREMENTS_TXT: analytics-cli/requirements/dev.txt
    environment:
      TARGET_DIR: /opt/app/analytics-cli
    volumes:
      - ./analytics/analytics-cli:/opt/app/analytics-cli

  api-lint:
    build:
      context: .
      dockerfile: shared/lint.Dockerfile
      args:
        SOURCE_DIR: api
        REQUIREMENTS_TXT: api/requirements/dev.txt
    environment:
      TARGET_DIR: /opt/app
    volumes:
      - ./api:/opt/app
