version: '3.8'

services:
  api:
    depends_on:
      - db
    volumes:
      - ./api:/opt/app

  web:
    build:
      context: web
      target: dev
    volumes:
      - ./web:/opt/app

  client:
    build:
      context: .
      dockerfile: shared/client.Dockerfile
    volumes:
      - ./client:/client/home
    depends_on:
      - api

  builder:
    build:
      context: .
      dockerfile: shared/builder.Dockerfile
    volumes:
      - ./client:/opt/client
