name: push

on: push

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Development Environment
        run: make build-dev run-dev

      - name: Run lint
        run: make run-lint

      - name: Run tests
        run: make run-tests
